#!/usr/bin/env python3

from __future__ import print_function

import sys
import os

from get_docker_secret import get_docker_secret

from dmoj.cli import main as cli_main
from dmoj.judge import main as judge_main

def main():
    if '-h' in sys.argv or '--help' in sys.argv:
        print('DMOJ Docker Image: run with argument `cli` to use `dmoj-cli`', file=sys.stderr)

    if len(sys.argv) > 1 and sys.argv[1] == 'cli':
        sys.argv = ['docker run ... cli', '-c', '/judge/judge.yml'] + sys.argv[2:]
        sys.exit(cli_main())
    else:
        site = os.environ.get('JUDGE_BRIDGED_HOST', 'host')
        judge_name = os.environ.get('JUDGE_NAME', 'judge')
        judge_key = get_docker_secret('judge_key', default='bad_secret')

        sys.argv = ['docker run ...', '-c', '/judge/judge.yml'] + [site, judge_name, judge_key]
        sys.exit(judge_main())

if __name__ == '__main__':
    main()
